name: Feature
description: Новая фича
title: "[Feat]: "
labels: ["feature"]
body:
  - type: input
    id: goal
    attributes: { label: Цель, placeholder: Что даёт пользователю? }
    validations: { required: true }
  - type: textarea
    id: scope
    attributes: { label: Объем, description: Экраны, состояния, ошибки }
  - type: input
    id: due
    attributes: { label: Дедлайн (ДД.ММ), placeholder: 31.10 }
