    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm i --no-audit --no-fund

      - name: Install EAS CLI
        run: npm i -g eas-cli

      - name: Login to EAS
        env:
          EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
        run: |
          if [ -z "$EAS_TOKEN" ]; then
            echo "❌ EAS_TOKEN secret отсутствует (пустой). Задай его в Settings → Secrets → Actions."
            exit 1
          fi
          echo "== login =="
          eas login --token "$EAS_TOKEN"
          echo "== whoami =="
          eas whoami

      - name: Show Expo config (debug)
        run: npx expo config --json || true

      - name: Trigger EAS Android preview build
        run: |
          eas build \
            --platform android \
            --profile preview \
            --non-interactive \
            --no-wait
