name: EAS Preview

on:
  pull_request:
    branches: [ "main" ]
  push:
    branches:
      - main
      - feature/**
  workflow_dispatch: {}

jobs:
  preview:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install deps (robust)
        run: |
          if [ -f package-lock.json ]; then
            npm ci || npm i
          else
            npm i
          fi

      - name: Expo/EAS login
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}

      - name: Preflight (init project non-interactive)
        run: |
          echo "== whoami ==" && eas whoami
          echo "== init ==" && eas init --non-interactive || true
          echo "== expo config json ==" && npx expo config --json || true
          echo "== eas --version ==" && eas --version

      - name: Build Android preview
        run: eas build --platform android --profile preview --non-interactive --no-wait

      - name: Build iOS preview
        run: eas build --platform ios --profile preview --non-interactive --no-wait
