 name: EAS Preview

 on:
   push:
     branches: [ feature/ci-check-2, main ]
   pull_request:

 jobs:
   android-preview:
     runs-on: ubuntu-latest
+    env:
+      # прокидываем токен в окружение на весь job
+      EAS_TOKEN: ${{ secrets.EAS_TOKEN }}
+      EXPO_TOKEN: ${{ secrets.EAS_TOKEN }}

     steps:
       - uses: actions/checkout@v4

       - name: Setup Node
         uses: actions/setup-node@v4
         with:
           node-version: 20

       - name: Install deps
         run: npm ci

-      - name: Debug whoami (before)
-        run: echo "== whoami ==" && eas whoami
+      - name: Login to EAS
+        run: |
+          echo "== login =="
+          # Явный логин токеном (без вывода токена в логи)
+          eas login --token "$EAS_TOKEN"
+          echo "== whoami =="
+          eas whoami

       - name: EAS version
         run: eas --version

       - name: Expo config (json)
         run: npx expo config --json || true

       - name: Build Android preview
         run: |
           eas build --platform android --profile preview --non-interactive --no-wait
