name: EAS Preview
on:
  pull_request:
    branches: ["main"]
jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
      - name: Install deps
        run: npm ci || npm i
      - uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EAS_TOKEN }}
      - name: Build Android preview
        run: npx eas build --platform android --profile preview --non-interactive --no-wait
      - name: Build iOS preview
        run: npx eas build --platform ios --profile preview --non-interactive --no-wait
